# Generated by Django 5.0.4 on 2024-06-24 20:50
import random

from django.db import migrations


class Migration(migrations.Migration):

    def generate_barcode(apps, schema_editor):
        Product = apps.get_model('main_app', 'Product')
        products = Product.objects.all()
        barcodes = random.sample(range(100000000, 1000000000), len(products))
        for i in range(len(products)):
            product = products[i]
            product.barcode = barcodes[i]
            product.save()

    def reverse_barcode(apps, schema_editor):
        Product = apps.get_model('main_app', 'Product')
        products = Product.objects.all()
        for product in products:
            product.barcode = 0
            product.save()

    dependencies = [
        ('main_app', '0004_product_barcode'),
    ]

    operations = [
    ]
