# Generated by Django 5.0.4 on 2024-08-03 11:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Astronaut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(120)])),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d+$'), django.core.validators.MaxLengthValidator(15)])),
                ('is_active', models.BooleanField(default=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('spacewalks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spacecraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(120)])),
                ('manufacturer', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('capacity', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('launch_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(120)])),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Planned', max_length=9, validators=[django.core.validators.MaxLengthValidator(9)])),
                ('launch_date', models.DateField()),
                ('astronauts', models.ManyToManyField(related_name='astronaut_mission', to='main_app.astronaut')),
                ('commander', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commander_mission', to='main_app.astronaut')),
                ('spacecraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spacecraft_mission', to='main_app.spacecraft')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
